package org.ejavdge.web.driver.jdk.socket;

import org.ejavdge.error.InvariantViolation;
import org.ejavdge.web.driver.jdk.stream.ByteStream;

import java.io.IOException;
import java.util.stream.IntStream;

/**
 * A {@link ByteStream} view over the raw bytes of a socket reply.
 * <p>
 * This class implements {@link ByteStream} and adapts a {@link Reply} — which
 * represents the response received over a socket — into a stream of byte
 * values. When {@link #content()} is called, an infinite {@link IntStream} is
 * created that reads bytes one at a time from the reply's underlying input
 * stream via {@link Reply#stream()}.
 * <p>
 * Because HTTP response bodies have no explicit end-of-stream marker at the
 * byte level, the stream is necessarily unbounded and relies on the caller (or
 * a decoding policy, such as
 * {@link org.ejavdge.web.driver.jdk.socket.body.WithLimitation} or
 * {@link org.ejavdge.web.driver.jdk.socket.body.WithChunks}) to limit how many
 * bytes are actually consumed.
 * <p>
 * If an {@link IOException} occurs while reading a byte, it is wrapped in an
 * {@link InvariantViolation} with the message
 * {@code "There is no bytes to read.\n"}. When the stream is closed, the
 * underlying reply's input stream is also closed; if that fails, an
 * {@link InvariantViolation} with the message
 * {@code "There is no socket to close.\n"} is thrown.
 */
public final class BytesOfReply implements ByteStream {

    /**
     * The socket reply whose bytes are exposed as a stream.
     */
    private final Reply rep;

    /**
     * Creates a new byte stream over the given socket reply.
     *
     * @param r the reply whose bytes will be exposed as a stream
     */
    public BytesOfReply(final Reply r) {
        this.rep = r;
    }

    /**
     * Returns an {@link IntStream} of the raw bytes read from the socket reply.
     * <p>
     * The stream is generated by repeatedly invoking
     * {@link java.io.InputStream#read()} on the reply's underlying stream. It
     * is infinite, so callers are expected to limit it or to terminate
     * consumption when enough bytes have been read.
     * <p>
     * If reading a byte fails with an {@link IOException}, the exception is
     * wrapped in an {@link InvariantViolation} with the message
     * {@code "There is no bytes to read.\n"}. When the stream is closed via
     * {@link IntStream#close()}, the underlying input stream is also closed;
     * any failure during closing is wrapped in an {@link InvariantViolation}
     * with the message {@code "There is no socket to close.\n"}.
     *
     * @return an infinite stream of byte values read from the reply
     * @throws InvariantViolation if an I/O error occurs while reading or while
     *         closing the underlying stream
     */
    @Override
    public IntStream content() throws InvariantViolation {
        final var stream = this.rep.stream();
        return IntStream.generate(() -> {
            try {
                return stream.read();
            } catch (final IOException e) {
                throw new InvariantViolation(
                    "There is no bytes to read.\n",
                    e
                );
            }
        }).onClose(() -> {
            try {
                stream.close();
            } catch (final IOException e) {
                throw new InvariantViolation(
                    "There is no socket to close.\n",
                    e
                );
            }
        });
    }
}
